ulabox_ruler_expression_list:
    path: /list
    defaults: { _controller: ulabox_ruler.controller.expression:listAction }

ulabox_ruler_expression_create:
    path: /create
    defaults: { _controller: ulabox_ruler.controller.expression:createAction }

ulabox_ruler_expression_update:
    path: /{id}/update
    defaults: { _controller: ulabox_ruler.controller.expression:updateAction }

ulabox_ruler_expression_delete:
    path: /{id}/delete
    defaults: { _controller: ulabox_ruler.controller.expression:deleteAction }

ulabox_ruler_expression_show:
    path: /{id}
    defaults: { _controller: ulabox_ruler.controller.expression:showAction }
